### ISSUE TITLE
Wi-Fi provisioning fails on ESP32 board with "Failed to allocate taskpool" error

### ISSUE THREAD

**Issue by jkeiththomson** [aws/amazon-freertos-ble-ios-sdk#10]
I checked out the master branches of amazon-freertos and amazon-freertos-ble-ios-sdk and did the usual configuration setup, including everything described in issue #9.

When I run the example iOS demo app, I get the bluetooth pairing popup but I don't get the list of local Wi-Fi networks.

The last thing reported in the ESP32 console log is: Failed to allocate taskpool job for list network request

Am I missing some configuration setting, perhaps? I did enable IOT_BLE_ENABLE_WIFI_PROVISIONING

**Comment by ravibhagavandas** [comment]
Hi jkeiththomson@
Possibly what happened was the MQTT demo ( enabled by default on FreeRTOS ), ran into completion and it deleted the taskpool resources as part of cleanup. MQTT demo by default runs over both BLE and WiFi so it runs as soon as you connect to BLE for WiFi provisioning.
You can choose not to run the demo on BLE by only setting `AWSIOT_NETWORK_TYPE_WIFI` in the config here:
https://github.com/aws/amazon-freertos/blob/master/vendors/espressif/boards/esp32/aws_demos/config_files/aws_demo_config.h#L52

**Comment by jkeiththomson** [comment]
Good call. That got me part of the way -- I could see the list of Wi-Fi networks but I couldn't join one.  So I enabled the OTA Update Demo instead of the MQTT Demo, and now I can sign in to a local Wi-Fi network.

Thanks!

**Comment by alexa-noxon** [comment]
Closing this thread.  Feel free to reopen or start a new thread if any other questions or issues come up!
