### ISSUE TITLE
 Get afrVersion spelled gatAfrVersionOfPeripheral

### ISSUE THREAD

**Issue by armandr** [aws/amazon-freertos-ble-ios-sdk#2]
If intentional, maybe a bit confusing?

The function name starts with *gat*, which in BLE terms it could suggest GATT.

But the source comments suggest it should bet *get*:

` /**
     Get afrVersion of the Amazon FreeRTOS `peripheral`
....
     */
    public func gatAfrVersionOfPeripheral(_ peripheral: CBPeripheral) `

**Comment by xuaninbox** [comment]
Thats indeed a typo, it should be getAfrVersionOfPeripheral. Thanks for pointing that out!

**Comment by sarenameas** [comment]
Commit addressing issue has been added to the repo. Closing this issue.
