### ISSUE TITLE
Published (demo) app in appstore

### ISSUE THREAD

**Issue by aiasmartakis** [aws/amazon-freertos-ble-ios-sdk#33]
We were using 'WifiConfig' from 'Massimiliano Angelino' from the App store, but is seems to have vanished. Is there another published application in the app store (based on this project?) that allows me to provision WiFI on aws freertos devices?

**Comment by aggarg** [comment]
This repository is an SDK, using which you can create applications. We do not publish any demo to the app store but you are free to publish your apps.
