### ISSUE TITLE
PIN-Based Bluetooth Connection without Default Popup

### ISSUE THREAD

**Issue by mukesh-simform** [aws/amazon-freertos-ble-ios-sdk#35]
**Requirement:**
* We need to implement authentication for a BLE connection. Currently, Peripheral broadcasts an intent for PIN-based pairing, and the device displays a popup to enter the PIN for pairing. However, we want to handle this process programmatically without displaying the default popup.

**Problem:**
* In Android, we can bypass the default OS popup and manage PIN-based authentication programmatically using the `setPin `method. However, in the iOS SDK, I haven't found a similar method that fulfills our requirement. It seems that there is no such method even in CBCentralManager.

Here are some threads indicating that achieving this in iOS is not possible
- https://developer.apple.com/forums/thread/703663
- https://stackoverflow.com/questions/23603083/ble-send-passkey-programmatically/23605848#23605848

We are using this SDK and would like to know how we can implement PIN-based authentication programmatically.

Please advise on how to proceed with this implementation.

**Comment by cookpate** [comment]
I would suggest revisiting the requirement, as your research has indicated that device pairing is transparent to iOS Apps using BLE.

Can the user pair their device for the first time only? After successfully pairing with short-term keys, bonding can be performed in order to store long-term keys. Bonding allows the device to be paired again without any user input.

**Comment by mukesh-simform** [comment]
Yes, very first time whenever the user tries to pair with the device. User has to enter the PIN and we want to handle that PIN programmatically instead of reveling that to user and taking input from user.

Once bonding is there then next time that bonding will allow user to perform pairing without any user input until the user unpairs that device

**Comment by cookpate** [comment]
I think the only way to avoid having the user enter a PIN is to use Just Works pairing by configuring the FreeRTOS device to have no human input/output capabilities. This should only show a user confirmation prompt on iOS to complete the pairing before bonding.

However, this process is susceptible to MITM during the pairing process, by-design.

**Comment by kstribrnAmzn** [comment]
Closing as there hasn't been action on this issue for several months. This also will not be added as a feature as this library is deprecated. For a more recommended set of solutions, please see the repository top-level README.
