### ISSUE TITLE
https://github.com/aws/amazon-freertos-ble-ios-sdk.git: No such file or directory

### ISSUE THREAD

**Issue by noblerabbit** [aws/amazon-freertos-ble-ios-sdk#6]
If I copy/paste the command from the instructions I get  No such file or directory.

$ pod 'AmazonFreeRTOS', :git => 'https://github.com/aws/amazon-freertos-ble-ios-sdk.git'
-bash: https://github.com/aws/amazon-freertos-ble-ios-sdk.git: No such file or directory

**Comment by xuaninbox** [comment]
It looks like you are trying to run this command in the terminal. It should actually be put into the Podfile after you do pod init for you project.

**Comment by xuaninbox** [comment]
https://www.appcoda.com/cocoapods/

**Comment by noblerabbit** [comment]
Thanks for fast reply.

I ended up doing this, as I was getting errors in xcode. But the instructions were not clear to me (i dont have much prior exp with cocoapods/xcode). First two commands in the tutorial are bash, the third is not. Would be helpful to add a sentence to clarify this in the tutorial.

I cloned https://github.com/aws/amazon-freertos-ble-ios-sdk.git and then added the local path to Podfile.

This is my Podfile. Is this how it should be? Thanks.
```
platform :ios, '11.0'
use_frameworks!

target 'AmazonFreeRTOSDemo' do
  pod 'Alertift'
  pod 'AmazonFreeRTOS', :path => '/my/local/path/to/amazon-freertos-ble-ios-sdk'
  pod 'AWSAuthUI', '2.6.35'
  pod 'AWSUserPoolsSignIn', '2.6.35'
  pod 'LicensePlist'
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'
  pod 'AWSCore', '2.6.35'
end
```

**Comment by xuaninbox** [comment]
Yes, this looks correct to me, but make sure you have a target named AmazonFreeRTOSDemo
