### ISSUE TITLE
pod is throwing the error: The SWIFT_VERSION is missing for "AWSMobileClient" & "CBORSWift".

### ISSUE THREAD

**Issue by Ajaykumar02** [aws/amazon-freertos-ble-ios-sdk#8]
For the latest cocoapod version(which is  1.6.1), when we try to do pod install with the provided link:
pod 'AmazonFreeRTOS', :git => 'https://github.com/aws/amazon-freertos-ble-ios-sdk.git'
we get the SWIFT_VERSION missing issue.

**Comment by Ajaykumar02** [comment]
We can fix the issue by downgrading the cocoapod version to (1.5.3).

**Comment by lt72** [comment]
@xuaninbox @Ajaykumar02 : it seems there still one remaining issue of using React with the native SDK. Please explain what the next steps are in this issue, so we keep all knowledge in one place.

**Comment by xuaninbox** [comment]
Hey, the root cause if this issue is the the SWIFT_VERSION is missing in the target build settings, after manually adding it and set it as 4.2, we are able to resolve this issue.

**Comment by Ajaykumar02** [comment]
@xuaninbox  Even though we add swift version inside podspec using post_install script as shown below,
post_install do |installer|
 ...
  config.build_settings['SWIFT_VERSION'] = '3.2'
 
Here we get linker error, and framework not found React. Adding post_install is causing linker error and we cannot add the SWIFT_VERSION, please can you check on this.

**Comment by xuaninbox** [comment]
After debuting with the user offline, the linker error is caused by a different issue when using with react.
